// SPDX-License-Identifier: GPL-3.0

pragma solidity ^0.8.0;

import "./openzeppelin-contracts/contracts/token/ERC20/IERC20.sol";
import "./openzeppelin-contracts/contracts/token/ERC721/ERC721.sol";
import "./openzeppelin-contracts/contracts/token/ERC721/extensions/ERC721Enumerable.sol";
import "./openzeppelin-contracts/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "./openzeppelin-contracts/contracts/utils/Context.sol";
import "./openzeppelin-contracts/contracts/utils/Counters.sol";
import "./openzeppelin-contracts/contracts/utils/Address.sol";
import "./IRegistrar.sol";


/**
 * @dev {Registrar} token, including:
 *
 *  - store info by verify owner
 *  - mint token ID
 */
contract Registrar is Context, ERC721Enumerable, ERC721URIStorage, IRegistrar {
    using Counters for Counters.Counter;
    
    Counters.Counter private _tokenIdTracker;

    bytes4 public constant OwnerSelector = bytes4(keccak256("owner()")); // 0x8da5cb5b
    bytes public constant OwnerData = abi.encodeWithSelector(OwnerSelector);

    // target ==> key ==> value
    mapping (address => mapping (bytes32 => bytes)) private _infos;

    /**
     * @dev Pause all token transfer.
     *
     * Token URIs will be autogenerated based on `baseURI` and their token IDs.
     * See {ERC721-tokenURI}.
     */
    constructor() ERC721("Registrar", "R") {
    }

    function isReceiptOwner(address owner, address target) public view returns (bool) {
        if (target == owner) {
            return true;
        }
        
        if (Address.isContract(target)) {
            // refer Address.functionStaticCall(target, OwnerData);
            // solhint-disable-next-line avoid-low-level-calls
            (bool success, bytes memory returndata) = target.staticcall(OwnerData);
            if (success) {
                address targetOwner = abi.decode(returndata, (address));
                if (targetOwner == owner) {
                    return true;
                }
            }
        }
        
        return false;
    }
    
    /**
     * @dev Throws if called by any account other than the owner of the target.
     */
    modifier onlyOwner(address target) {
        require(isReceiptOwner(_msgSender(), target), "Registrar: caller is not the owner of target");
        _;
    }

    
    /**
     * @dev See {IERC721Metadata-tokenURI}.
     */
    function tokenURI(uint256 tokenId) public view override(ERC721, ERC721URIStorage) returns (string memory) {
        return super.tokenURI(tokenId);
    }

    function setTokenURI(uint256 tokenId, string memory _tokenURI) public onlyOwner(ownerOf(tokenId)) {
        _setTokenURI(tokenId, _tokenURI);
    }
    
    /**
     * @dev Check whether `tokenId` exists.
     */
    function exists(uint256 tokenId) public view returns (bool) {
        return _exists(tokenId);
    }

    /**
     * @dev Creates a new token for `to`. Its token ID will be automatically
     * assigned (and available on the emitted {IERC721-Transfer} event), and the token
     * URI autogenerated based on the base URI passed at construction.
     *
     * See {ERC721-_mint}.
     *
     * Requirements:
     *
     * - the caller must have the `MINTER_ROLE`.
     */    
    function mint(address to) public onlyOwner(to)  {
        uint256 tokenId = _tokenIdTracker.current();
        _tokenIdTracker.increment();
        
        
        _mint(to, tokenId);
        
    }
    function mintWithTokenURI(address to, string memory _tokenURI) public onlyOwner(to) {
        _mint(to, _tokenIdTracker.current());
        _setTokenURI(_tokenIdTracker.current(), _tokenURI);
        _tokenIdTracker.increment();
    }
    function tryMint(address to) internal {
        if (balanceOf(to) == 0) {
            uint256 tokenId = _tokenIdTracker.current();
            _tokenIdTracker.increment();
            
            _mint(to, tokenId);
        }
    }
   
    function updateEntry(address target, bytes32 key, bytes memory value) override onlyOwner(target) public returns (bool) {
        _infos[target][key] = value;
        
        emit Updated(_msgSender(), target, key, value);

        tryMint(target);

        return true;
    }
    
    function getEntry(address target, bytes32 key) public view override returns (bytes memory value) {
        return _infos[target][key];
    }
    
    /**
     * @dev See {ERC721URIStorage}.
     */
    function _burn(uint256 tokenId) internal virtual override(ERC721, ERC721URIStorage) {
        super._burn(tokenId);
    }
    
    function _beforeTokenTransfer(address from, address to, uint256 tokenId) internal override(ERC721, ERC721Enumerable) {
        require(from == address(0), "ERC721Pausable: only mint is allowed");    // force disable transfer
        super._beforeTokenTransfer(from, to, tokenId);
    }

    /**
     * @dev See {IERC165-supportsInterface}.
     */
    function supportsInterface(bytes4 interfaceId) public view override(ERC721, ERC721Enumerable) returns (bool) {
        return interfaceId == type(IRegistrar).interfaceId
            || super.supportsInterface(interfaceId);
    }
}